services:
  - type: web
    name: risklytics
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn -w 1 -k gthread --timeout 30 --keep-alive 2 -b 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DILISENSE_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CSE_ID
        sync: false
      - key: DART_API_KEY
        sync: false
    healthCheckPath: /healthz
    autoDeploy: false
